services:
  postgres:
    image: postgres
    container_name: ivr_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ivr_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: